// DO NOT EDIT THIS FILE MANUALLY
// YOU MUST UPDATE CONSTRAINTS IN problem.toml

#pragma once

const long long int MIN_N = 2;
const long long int MAX_N = 1000;
const long long int MIN_M = 1;
const long long int MAX_M = 1000;
const long long int MIN_W = 0;
const long long int MAX_W = 100000000;